/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ACER
 */

import com.toedter.calendar.JDateChooser;
import controller.DataDokterController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JTable;

public class vAdminPage extends javax.swing.JFrame {
    private DataDokterController dc;
    int PosisiLogin;
    /**
     * Creates new form vAdminPage
     */
    public vAdminPage(int PosisiLogin) {
        this.PosisiLogin = PosisiLogin;
        initComponents();
        dc = new DataDokterController(this);
        dc.fillTableDataDokter();
    }

    private vAdminPage() {
        initComponents();
        dc = new DataDokterController(this);
        dc.fillTableDataDokter();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFNoTelp = new javax.swing.JTextField();
        jTFNama = new javax.swing.JTextField();
        jTFID = new javax.swing.JTextField();
        jTFAlamat = new javax.swing.JTextField();
        jTFJenis = new javax.swing.JTextField();
        jTFHarga = new javax.swing.JTextField();
        jDateChooserTanggalLahir = new com.toedter.calendar.JDateChooser();
        AddButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        GoToDataAkun = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        GoToDataPasien1 = new javax.swing.JButton();
        logout2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "No Telp", "Tanggal Lahir", "Alamat", "Jenis", "Harga"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("DATA DOKTER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("No Telp");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tanggal Lahir");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Jenis");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Alamat");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Harga");

        jTFID.setEditable(false);

        jTFJenis.setToolTipText("");

        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        EditButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        RemoveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        GoToDataAkun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GoToDataAkun.setText("Data Akun");
        GoToDataAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToDataAkunActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        GoToDataPasien1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GoToDataPasien1.setText("Data Pasien");
        GoToDataPasien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToDataPasien1ActionPerformed(evt);
            }
        });

        logout2.setBackground(new java.awt.Color(255, 0, 0));
        logout2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout2.setText("LOG OUT");
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTFJenis, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTFAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTFID, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTFNama, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTFNoTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jDateChooserTanggalLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddButton)
                            .addComponent(GoToDataPasien1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GoToDataAkun)
                            .addComponent(RemoveButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(logout2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserTanggalLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTFJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTFHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton)
                            .addComponent(RemoveButton)
                            .addComponent(EditButton))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoToDataAkun)
                            .addComponent(clearBtn)
                            .addComponent(GoToDataPasien1))))
                .addGap(18, 18, 18)
                .addComponent(logout2)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        if (jTFID.getText().isEmpty() == false){
            JOptionPane.showMessageDialog(null, "Data Sudah Ada");
            return;
        }
        dc.insert();
        dc.fillTableDataDokter();
        jTFAlamat.setText("");
        jTFHarga.setText("");
        jTFID.setText("");
        jTFJenis.setText("");
        jTFNama.setText("");
        jTFNoTelp.setText("");
        jDateChooserTanggalLahir.setDate(null);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        dc.delete();
        dc.fillTableDataDokter();
        jTFAlamat.setText("");
        jTFHarga.setText("");
        jTFID.setText("");
        jTFJenis.setText("");
        jTFNama.setText("");
        jTFNoTelp.setText("");
        jDateChooserTanggalLahir.setDate(null);
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        dc.update();
        dc.fillTableDataDokter();
        jTFAlamat.setText("");
        jTFHarga.setText("");
        jTFID.setText("");
        jTFJenis.setText("");
        jTFNama.setText("");
        jTFNoTelp.setText("");
        jDateChooserTanggalLahir.setDate(null);
    }//GEN-LAST:event_EditButtonActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
//        int baris = jTable.getSelectedRow();   
//        jTFID.setText(jTable.getValueAt(baris, 0).toString());
//        jTFNama.setText(jTable.getValueAt(baris, 1).toString());
//        jTFNoTelp.setText(jTable.getValueAt(baris, 2).toString());
//        
//        String tanggal = jTable.getValueAt(baris, 3).toString();
//        try {
//            SimpleDateFormat dateFormatTabel = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal dari tabel
//            SimpleDateFormat dateFormatChooser = new SimpleDateFormat("dd-MM-yyyy "); // Format tanggal untuk JDateChooser
//
//            Date parsedDate = dateFormatTabel.parse(tanggal);
//            String formattedDate = dateFormatChooser.format(parsedDate);
//
//            Date date = dateFormatChooser.parse(formattedDate);
//            //jDateChooser.setDate(date);
//            jDateChooserTanggalLahir.setDate(date);
//        } catch (ParseException e) {
//            e.printStackTrace();
//        }
        int row = jTable.getSelectedRow();
        int idDokter = (int) jTable.getValueAt(row, 0);
        dc.getDataDokterById(idDokter);
    }//GEN-LAST:event_jTableMouseClicked

    private void GoToDataAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToDataAkunActionPerformed
        // TODO add your handling code here:
        new vAkun(PosisiLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoToDataAkunActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        jTFAlamat.setText("");
        jTFHarga.setText("");
        jTFID.setText("");
        jTFJenis.setText("");
        jTFNama.setText("");
        jTFNoTelp.setText("");
        jDateChooserTanggalLahir.setDate(null);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void GoToDataPasien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToDataPasien1ActionPerformed
        // TODO add your handling code here:
        new vPasien(PosisiLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoToDataPasien1ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        vLoginPage l = new vLoginPage();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vAdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton GoToDataAkun;
    private javax.swing.JButton GoToDataPasien1;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton clearBtn;
    private com.toedter.calendar.JDateChooser jDateChooserTanggalLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAlamat;
    private javax.swing.JTextField jTFHarga;
    private javax.swing.JTextField jTFID;
    private javax.swing.JTextField jTFJenis;
    private javax.swing.JTextField jTFNama;
    private javax.swing.JTextField jTFNoTelp;
    private javax.swing.JTable jTable;
    private javax.swing.JToggleButton logout1;
    private javax.swing.JToggleButton logout2;
    // End of variables declaration//GEN-END:variables

    
    public JButton getjButtonAdd() {
        return AddButton;
    }

    public JButton getjButtonEdit() {
        return EditButton;
    }

    public JButton getjButtonRemove() {
        return RemoveButton;
    }

    public JButton getjButtonGoToDataPasien() {
        return GoToDataAkun;
    }

    public JTable getjTable() {
        return jTable;
    }

    public JTextField getjTFAlamat() {
        return jTFAlamat;
    }

    public JTextField getjTFHarga() {
        return jTFHarga;
    }

    public JTextField getjTFID() {
        return jTFID;
    }

    public JTextField getjTFJenis() {
        return jTFJenis;
    }

    public JTextField getjTFNama() {
        return jTFNama;
    }

    public JTextField getjTFNoTelp() {
        return jTFNoTelp;
    }

    public JDateChooser getjDateChooserTanggalLahir() {
        return jDateChooserTanggalLahir;
    }


}
