/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ACER
 */

import controller.DataAkunController;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JOptionPane;

public class vAkun extends javax.swing.JFrame {
    private DataAkunController dc;
    int PosisiLogin;
    /**
     * Creates new form vAkun
     */
    public vAkun(int PosisiLogin) {
        this.PosisiLogin = PosisiLogin;
        initComponents();
        dc = new DataAkunController(this);
        dc.fillTableDataAkun();
    }

    private vAkun() {
        initComponents();
        dc = new DataAkunController(this);
        dc.fillTableDataAkun();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoToDataPasien = new javax.swing.JButton();
        jTFPassword = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        jTFUsername = new javax.swing.JTextField();
        jTFID = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EditButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        RemoveButton = new javax.swing.JButton();
        GoToDataDokter = new javax.swing.JButton();
        ChoiceForm = new javax.swing.JComboBox<>();
        logout2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GoToDataPasien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GoToDataPasien.setText("Data Pasien");
        GoToDataPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToDataPasienActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jTFID.setEditable(false);

        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Password", "Posisi"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("AKUN MANAJEMEN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Username");

        EditButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Posisi");

        RemoveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        GoToDataDokter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GoToDataDokter.setText("Data Dokter");
        GoToDataDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToDataDokterActionPerformed(evt);
            }
        });

        ChoiceForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dokter", "admin", "akuntan", "pendaftaran" }));
        ChoiceForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoiceFormActionPerformed(evt);
            }
        });

        logout2.setBackground(new java.awt.Color(255, 0, 0));
        logout2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout2.setText("LOG OUT");
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFID, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(jTFUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(jTFPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(ChoiceForm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(GoToDataPasien)
                                    .addComponent(AddButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RemoveButton)
                                    .addComponent(GoToDataDokter)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(logout2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ChoiceForm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton)
                            .addComponent(RemoveButton)
                            .addComponent(EditButton))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoToDataPasien)
                            .addComponent(clearBtn)
                            .addComponent(GoToDataDokter))
                        .addGap(18, 18, 18)
                        .addComponent(logout2)))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoToDataPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToDataPasienActionPerformed
        // TODO add your handling code here:
        new vPasien(PosisiLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoToDataPasienActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        jTFID.setText("");
        jTFUsername.setText("");
        jTFPassword.setText("");
        ChoiceForm.setSelectedIndex(0);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        if (jTFID.getText().isEmpty() == false){
            JOptionPane.showMessageDialog(null, "Data Sudah Ada");
            return;
        }
        dc.insert();
        dc.fillTableDataAkun();
        jTFID.setText("");
        jTFUsername.setText("");
        jTFPassword.setText("");
        ChoiceForm.setSelectedIndex(0);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        //        int baris = jTable.getSelectedRow();
        //        jTFID.setText(jTable.getValueAt(baris, 0).toString());
        //        jTFNama.setText(jTable.getValueAt(baris, 1).toString());
        //        jTFNoTelp.setText(jTable.getValueAt(baris, 2).toString());
        //
        //        String tanggal = jTable.getValueAt(baris, 3).toString();
        //        try {
            //            SimpleDateFormat dateFormatTabel = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal dari tabel
            //            SimpleDateFormat dateFormatChooser = new SimpleDateFormat("dd-MM-yyyy "); // Format tanggal untuk JDateChooser
            //
            //            Date parsedDate = dateFormatTabel.parse(tanggal);
            //            String formattedDate = dateFormatChooser.format(parsedDate);
            //
            //            Date date = dateFormatChooser.parse(formattedDate);
            //            //jDateChooser.setDate(date);
            //            jDateChooserTanggalLahir.setDate(date);
            //        } catch (ParseException e) {
            //            e.printStackTrace();
            //        }
        int row = jTable.getSelectedRow();
        int idAkun = (int) jTable.getValueAt(row, 0);
        dc.getDataAkunById(idAkun);
    }//GEN-LAST:event_jTableMouseClicked

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        dc.update();
        dc.fillTableDataAkun();
        jTFID.setText("");
        jTFUsername.setText("");
        jTFPassword.setText("");
        ChoiceForm.setSelectedIndex(0);
    }//GEN-LAST:event_EditButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        dc.delete();
        dc.fillTableDataAkun();
        jTFID.setText("");
        jTFUsername.setText("");
        jTFPassword.setText("");
        ChoiceForm.setSelectedIndex(0);
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void GoToDataDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToDataDokterActionPerformed
        // TODO add your handling code here:
        new vAdminPage(PosisiLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoToDataDokterActionPerformed

    private void ChoiceFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoiceFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChoiceFormActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        vLoginPage l = new vLoginPage();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JComboBox<String> ChoiceForm;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton GoToDataDokter;
    private javax.swing.JButton GoToDataPasien;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFID;
    private javax.swing.JTextField jTFPassword;
    private javax.swing.JTextField jTFUsername;
    private javax.swing.JTable jTable;
    private javax.swing.JToggleButton logout2;
    // End of variables declaration//GEN-END:variables
    
    public JTable getjTable() {
        return jTable;
    }
    
    public JTextField getjTFUsername() {
        return jTFUsername;
    }
    

    // Getter method for jTFID
    public JTextField getjTFID() {
        return jTFID;
    }

    
    // Getter method for jTFPassword
    public JTextField getjTFPassword() {
        return jTFPassword;
    }
    
    
    // Getter method for ChoiceForm
    public JComboBox getPosisi() {
        return ChoiceForm;
    }
    
}
