/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ACER
 */
import java.sql.SQLException;
import javax.swing.JOptionPane;
import DAOuser.UserDAO;
import model.DataUser;
import koneksi.connector;

public class vLoginPage extends javax.swing.JFrame {
    
    
    public vLoginPage() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField = new javax.swing.JPasswordField();
        jTUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jTUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsernameActionPerform(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DFPOP1-W9", 0, 48)); // NOI18N
        jLabel1.setText("SICK HOUSE");

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setLabel("MASUK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasukActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(388, 388, 388))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(584, 584, 584))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(490, 490, 490))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jTUsername.getAccessibleContext().setAccessibleName("");
        jTUsername.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasukActionPerformed
        // TODO add your handling code here:
        String username = jTUsername.getText();
        String password = new String(jPasswordField.getPassword());
        int PosisiLogin;
        UserDAO dao = new UserDAO();
        try{
            connector.connection();
            DataUser data = dao.loginUser(username, password);
            if(data == null){
                JOptionPane.showMessageDialog(rootPane, "Username atau password salah!");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Login Berhasil!" + "\n" + "Username Anda : " + data.getUsername() + "\n" + "Posisi Anda : " + data.getPosition());
                String position = data.getPosition();
                //    0 = admin => add, edit, clr, archives, back(admin page)
                //    1 = dokter => archives
                //    2 = pendaftaran => add, edit, clr, "sudah pernah"
                switch(position){
                    case "admin":
                        PosisiLogin = 0;
                        new vAdminPage(PosisiLogin).setVisible(true);
                        this.dispose();
                        break;
                    case "pendaftaran":
                        PosisiLogin = 2;
                        new vPasien(PosisiLogin).setVisible(true);
                        this.dispose();
                        break;
                    case "dokter":
                        PosisiLogin = 1;
                        new vPendaftaran(PosisiLogin).setVisible(true);
                        this.dispose();
                        break;
                    case "akuntan":
                       new vPembayaran().setVisible(true);
                       this.dispose();
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Posisi Anda tidak diketahui!");
                        break;
                }
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonMasukActionPerformed

    private void jTUsernameActionPerform(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsernameActionPerform
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsernameActionPerform

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new vLoginPage().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTUsername;
    // End of variables declaration//GEN-END:variables
}
